[package]
name = "duf"
version = "0.1.0"
edition = "2021"
authors = ["sigoden <sigoden@gmail.com>"]
description = "Duf is a simple file server."
license = "MIT OR Apache-2.0"
homepage = "https://github.com/sigoden/duf"
repository = "https://github.com/sigoden/duf"
autotests = false
categories = ["command-line-utilities", "web-programming::http-server"]
keywords = ["static", "file", "server", "upload", "http", "cli"]

[dependencies]
clap = { version = "3", default-features = false, features = ["std", "cargo"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs", "io-util"]}
hyper = { version = "0.14", features = ["http1", "server", "tcp", "stream"] }
percent-encoding = "2.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio-util = { version = "0.7", features = ["codec", "io-util"] }
futures = "0.3"
base64 = "0.13.0"

[profile.release]
lto = true
strip = true
opt-level = "z"
